-- 11_pareto_summary.sql
-- Pareto summary:
-- 1) Revenue share generated by top 20% customers
-- 2) Percentage of customers needed to reach 80% of total revenue

WITH customer_rev AS (
  SELECT
    o.customer_id,
    SUM(oi.quantity * oi.item_amount) AS customer_revenue
  FROM orders o
  JOIN order_items oi
    ON oi.order_id = o.order_id
  GROUP BY o.customer_id
),

ranked AS (
  SELECT
    customer_id,
    customer_revenue,
    ROW_NUMBER() OVER (ORDER BY customer_revenue DESC) AS rn,
    COUNT(*) OVER () AS total_customers,
    CEIL(0.2 * COUNT(*) OVER ()) AS top_n,
    SUM(customer_revenue) OVER () AS total_revenue,
    SUM(customer_revenue) OVER (
      ORDER BY customer_revenue DESC
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) * 1.0
    / NULLIF(SUM(customer_revenue) OVER (), 0) AS cumulative_share
  FROM customer_rev
),

cutoff AS (
  SELECT
    MIN(rn) AS cutoff_rn
  FROM ranked
  WHERE cumulative_share >= 0.80
),

summary_base AS (
  SELECT
    MAX(total_customers) AS total_customers,
    MAX(total_revenue) AS total_revenue,
    MAX(top_n) AS top_n,
    MAX(cutoff_rn) AS cutoff_rn,
    SUM(CASE WHEN rn <= top_n THEN customer_revenue ELSE 0 END) AS top20_revenue
  FROM ranked
  CROSS JOIN cutoff
)

SELECT
  total_customers,
  total_revenue,
  top_n,
  top20_revenue,
  ROUND(top20_revenue * 1.0 / NULLIF(total_revenue, 0), 4) AS top20_share,
  cutoff_rn AS customers_needed_for_80,
  ROUND(cutoff_rn * 1.0 / NULLIF(total_customers, 0), 4) AS pct_customers_needed_for_80
FROM summary_base;
